### ISSUE TITLE
flow.json only works with working Cloudant

### ISSUE THREAD

**Issue by hphde** [node-red/node-red-bluemix-starter#5]
I removed Cloudant and Redis and tried to push my app without it but including flows in flow.json. Unfortunately they didn't appear as expected. Would be good if it works without it. If _not_ it would be good that it's mentioned that flow.json requires Cloudant.

**Comment by knolleary** [comment]
Hi, the readme already says:

> It will automatically create an instance of the Cloudant service, call it sample-node-red-cloudantNoSQLDB and bind it to you app. **This is where your Node-RED instance will store its data.** If you deploy multiple instances of Node-RED from this repository, they will share the one Cloudant instance.

But I have added a bit more further down where it talks about `flow.json`: https://github.com/node-red/node-red-bluemix-starter/commit/f349d5e5090b8fc948c50ece6d246a4a02aaae4a
